version: 2.1
jobs:
  build:
    working_directory: ~/sunbird-epub-player
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout:
          path: ~/sunbird-epub-player
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          environment:
            NG_CLI_ANALYTICS: "ci"
          command: npm install
      - run: cd projects/sunbird-epub-player &&  npm install
      - run:
          name: Node install
          command:  npm install
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test
      - run:
          name: Install  Node.js v14.20.0 with build in nvm tool
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v14 && nvm use v14 && nvm alias default v14
            node -v
      - run:
          name: Alter Node version
          command: 'node --version' 
      - run:
          name: Install sonar scanner
          command: ' npm install -i -g sonarqube-scanner'
      - run:
          name: Sonar scanner
          command: cd ~/sunbird-epub-player && sonar-scanner 
      - run:
          name: Publish to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
              npm run build-lib && npm pack ./dist/sunbird-epub-player
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm publish project-sunbird-sunbird-epub-player-v9-*
            else
              npm run build-lib && npm pack ./dist/sunbird-epub-player
            fi
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
